### ISSUE TITLE
How to compile for Windows?

### ISSUE THREAD

**Issue by kiner-shah** [Isembart/Boids-Simulation-SFML#8]
I would like to help but currently the project only supports Linux. I would like to compile it for Windows. I checked the CMakeLists.txt but some code related to Windows is commented.
I think it would be a good idea to add support for Windows.

**Comment by Isembart** [comment]
Hi. In fact I used to develop this project on Windows 11 and I didn't even test if it works on linux.
To compile it you should use CMake with your preferred generator.
I use:
`cmake -G "MinGW Makefiles" ..` while beeing in build/ directory located inside project folder
then execute `make` in this directory 

Commented code were used to move OpenAL DLL which does not exist and OpenAL is as a static library.
The project should compile correctly. Can you provide me with error message?

**Comment by kiner-shah** [comment]
Aah, you compiled with MinGW. I meant using MSVC compiler.

**Comment by Isembart** [comment]
I could build the project with msvc after creating files for Visual Studio 2022

Does it work for you?
